version: '3'
services:
  frontend:
    build: frontend/
    working_dir: /app/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: yarn start
    volumes:
      - ./frontend:/app/frontend
      - frontend_node_modules:/app/frontend/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

volumes:
  frontend_node_modules: